Repository FoyerD/Gamazon, pull requests merged in 2025-06, with the labels that each got.

#372 Enhance Receipt and ReceiptProduct classes to include product names. …
  src/main/java/Domain/Shopping/Receipt.java
  src/main/java/Domain/Shopping/ReceiptProduct.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaShoppingBasketRepository.java
Labels: bug, DBs

#374 363 add persistence for permission
  src/main/bundles/dev.bundle
  src/main/java/Domain/management/Permission.java
  src/main/java/Domain/management/PermissionId.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaPermissionRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaPermissionRepository.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryPermissionRepository.java
  src/main/java/UI/DatabaseCleaner.java
  src/test/java/PermissionTest.java
  vite.config.ts.timestamp-1748779322759-464cbcebc5fc6.mjs
Labels: enhancement, DBs

#378 377 add persistence for notifications
  log.txt.lck
  src/main/bundles/dev.bundle
  src/main/java/Domain/Notification/Notification.java
  src/main/java/Domain/Repos/ILockbasedRepository.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/Store.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaNotificationRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaNotificationRepository.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryNotificationRepository.java
  src/main/java/UI/DatabaseRelated/DatabaseCleaner.java
Labels: bug, enhancement, DBs

#383 382 integrating shipping mechanism
  src/main/java/Domain/ExternalServices/IExternalSupplyService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/Shopping/CheckoutManager.java
  src/main/java/Domain/Shopping/IShoppingCartFacade.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Infrastructure/ExternalSupplyService.java
Labels: enhancement, domain

#381 373 adding needed tests
  src/main/java/Domain/Store/Policy.java
  src/test/java/Domain/Shopping/ReceiptTest.java
  src/test/java/Domain/Shopping/ShoppingBasketTest.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
  src/test/java/Domain/Shopping/ShoppingCartTest.java
  src/test/java/Domain/Store/PolicyFacadeTest.java
  src/test/java/Domain/Store/PolicyTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/PolicyServiceTest.java
Labels: enhancement, tests

#387 fixed it
  log.txt.lck
  src/main/java/Application/ServiceManager.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/IRepoManager.java
  src/main/java/Domain/management/PolicyFacade.java
  src/main/java/Infrastructure/MemoryRepoManager.java
  src/test/java/MarketServiceTest.java
  src/test/java/StoreTests/PolicyServiceTest.java
  src/test/java/StoreTests/PolicyServiceTests.java
Labels: enhancement, refactoring, tests

#388 Added policy to managers (testing)
  src/main/java/Application/DTOs/PolicyDTO.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/IRepoManager.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Infrastructure/MemoryRepoManager.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
Labels: enhancement

#395 finished implemeting support for birthdate in registration
  log.txt.lck
  src/main/java/Application/DTOs/UserDTO.java
  src/main/java/Application/UserService.java
  src/main/java/Domain/User/Guest.java
  src/main/java/Domain/User/LoginManager.java
  src/main/java/Domain/User/Member.java
  src/main/java/UI/presenters/ILoginPresenter.java
  src/main/java/UI/presenters/LoginPresenter.java
  src/main/java/UI/views/RegisterView.java
  src/main/java/UI/views/UserProfileView.java
Labels: enhancement, GUI, domain

#397 Generalize the notification to all the views
  log.txt.lck
  src/main/bundles/dev.bundle
  src/main/java/UI/views/BaseView.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/CheckoutView.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/ManagerView.java
  src/main/java/UI/views/OwnerView.java
  src/main/java/UI/views/ProductReviewView.java
  src/main/java/UI/views/RegisterView.java
  src/main/java/UI/views/StoreSearchView.java
  src/main/java/UI/views/TradingView.java
  src/main/java/UI/views/UserProfileView.java
Labels: enhancement, refactoring

#399 Add register and logout buttons to HomePageView; enhance ban handling…
  src/main/java/UI/views/HomePageView.java
Labels: bug

#401 Finished read me and reafctoring the init.JSON and appInitializer
  README.md
  pom.xml
  src/main/bundles/dev.bundle
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Infrastructure/ExternalPaymentService.java
  src/main/java/Infrastructure/ExternalSupplyService.java
  src/main/java/UI/AppInitializer.java
  src/main/java/UI/DatabaseRelated/DbHealthStatus.java
  src/main/resources/config/init.json
Labels: enhancement, refactoring

#403 Add user ban status check functionality
  src/main/java/Application/MarketService.java
  src/main/java/UI/presenters/IUserSessionPresenter.java
  src/main/java/UI/presenters/UserSessionPresenter.java
  src/main/java/UI/views/CartView.java
Labels: bug

#406 393 check store polices
  log.txt.lck
  src/main/bundles/dev.bundle
  src/main/java/Application/DTOs/PolicyDTO.java
  src/main/java/Application/PolicyService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Domain/Shopping/IShoppingCartFacade.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/management/PolicyFacade.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenter.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/UserProfileView.java
  src/main/java/UI/views/components/BasketLayout.java
  src/test/java/Domain/Store/PolicyFacadeTest.java
  src/test/java/StoreTests/PolicyServiceTests.java
Labels: enhancement, GUI, domain

#411 410 refactor bid
  log.txt.lck
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/Store/StoreFacade.java
  src/test/java/StoreTests/StoreFacadeTests.java
Labels: store, refactoring, tests

#416 409 implement offer
  src/main/bundles/dev.bundle
  src/main/java/Application/DTOs/OfferDTO.java
  src/main/java/Application/DTOs/PaymentDetailsDTO.java
  src/main/java/Application/DTOs/UserDTO.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/IRepoManager.java
  src/main/java/Domain/Repos/IOfferRepository.java
  src/main/java/Domain/Shopping/Offer.java
  src/main/java/Domain/Shopping/OfferManager.java
  src/main/java/Domain/Shopping/PaymentDetails.java
  src/main/java/Domain/Store/Policy.java
  src/main/java/Domain/User/LoginManager.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/Infrastructure/MemoryRepoManager.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryOfferRepository.java
  src/main/java/UI/presenters/IManagementPresenter.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/main/java/UI/presenters/PurchasePresenter.java
  src/main/java/UI/views/ManagerView.java
  src/main/java/UI/views/StoreSearchView.java
  src/main/java/UI/views/components/ItemLayout.java
  src/main/java/UI/views/components/MakeOfferDialog.java
  src/main/java/UI/views/components/OfferLayout.java
  src/main/java/UI/views/components/PoliciesLayout.java
  src/main/java/UI/views/components/StoreLayout.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/PolicyServiceTests.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: enhancement, GUI, domain

#418 417 add persistence to offer in db
  src/main/bundles/dev.bundle
  src/main/java/Domain/Shopping/Offer.java
  src/main/java/Domain/Shopping/PaymentDetails.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaOfferRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaOfferRepository.java
  src/main/java/UI/DatabaseRelated/DatabaseCleaner.java
Labels: DBs

#428 405 add persistence to discounts in db
  src/main/java/Domain/Store/Discounts/AndDiscount.java
  src/main/java/Domain/Store/Discounts/CompositeDiscount.java
  src/main/java/Domain/Store/Discounts/Conditions/AndCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/CompositeCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/Condition.java
  src/main/java/Domain/Store/Discounts/Conditions/MaxPriceCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/MaxQuantityCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/MinPriceCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/MinQuantityCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/OrCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/SimpleCondition.java
  src/main/java/Domain/Store/Discounts/Conditions/TrueCondition.java
  src/main/java/Domain/Store/Discounts/Discount.java
  src/main/java/Domain/Store/Discounts/IDiscountRepository.java
  src/main/java/Domain/Store/Discounts/OrDiscount.java
  src/main/java/Domain/Store/Discounts/Qualifiers/CategoryQualifier.java
  src/main/java/Domain/Store/Discounts/Qualifiers/DiscountQualifier.java
  src/main/java/Domain/Store/Discounts/Qualifiers/ProductQualifier.java
  src/main/java/Domain/Store/Discounts/Qualifiers/StoreQualifier.java
  src/main/java/Domain/Store/Discounts/SimpleDiscount.java
  src/main/java/Domain/Store/Discounts/XorDiscount.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaDiscountRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaDiscountRepository.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryDiscountRepository.java
  src/main/java/UI/DatabaseRelated/DatabaseCleaner.java
  src/test/java/Domain/Store/Discounts/Qualifiers/DiscountQualifierTest.java
  src/test/java/ShoppingServiceTest.java
Labels: enhancement, DBs

#441 did it
  README.md
  src/main/bundles/dev.bundle
  src/main/java/UI/AppInitializer.java
  src/main/resources/application.properties
  src/main/resources/config/init.json
Labels: refactoring

#451 added functionality
  log.txt.1
  log.txt.lck
  src/main/bundles/dev.bundle
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/StoreSearchView.java
  src/main/java/UI/views/components/ItemLayout.java
  src/main/java/UI/views/components/StoreBrowser.java
  src/main/java/UI/views/components/StoreItemPreview.java
  src/main/java/UI/views/components/StoreLayout.java
  src/main/java/UI/views/components/StoreTile.java
Labels: enhancement, GUI

#456 455 discount tests in marketserivice
  log.txt.lck
  src/main/java/Application/utils/Response.java
  src/test/java/MarketServiceTest.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: tests

#457 450 improving the new feature must have
  log.txt.1
  src/main/bundles/dev.bundle
  src/main/java/UI/views/GIFView.java
  src/main/java/UI/views/HomePageView.java
  src/main/resources/static/images/esterEgg.png
Labels: enhancement

#464 finished null id bug
  log.txt.lck
  src/main/java/Domain/Store/Discounts/DiscountBuilder.java
  src/main/java/UI/views/ManagerView.java
  src/test/java/Domain/Store/Discounts/DiscountBuilderTest.java
Labels: bug, GUI
