Repository FoyerD/Gamazon, pull requests merged in 2025-05, with the labels that each got.

#142 Added synch mechanism to itemRepo/Facade.
  log.txt
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/Infrastructure/Repositories/MemoryItemRepository.java
  src/test/java/Domain/Store/ItemFacadeTest.java
  src/test/java/StoreTests/ItemServiceTests.java
Labels: store

#145 finished docs for user agg
  src/main/java/Application/UserService.java
  src/main/java/Domain/TokenService.java
  src/main/java/Domain/User/Guest.java
  src/main/java/Domain/User/IUserRepository.java
  src/main/java/Domain/User/LoginManager.java
  src/main/java/Domain/User/Member.java
  src/main/java/Domain/User/PasswordChecker.java
  target/classes/Domain/User/Guest.class
  target/classes/Domain/User/LoginManager.class
Labels: documentation, users

#146 fixed ShoppingServiceTest
  src/test/java/ShoppingServiceTest.java
Labels: bug, shopping

#148 i am done
  src/main/java/Application/DTOs/OrderDTO.java
  src/main/java/Application/ShoppingService.java
Labels: bug, shopping

#155 150 integrate spring boot with vaadin and mvp architecture
  src/main/java/UI/presenters/ILoginPresenter.java
  src/main/java/UI/presenters/IManagementPresenter.java
  src/main/java/UI/presenters/IMarketPresenter.java
  src/main/java/UI/presenters/IProductPresenter.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/IStorePresenter.java
  src/main/java/UI/views/MainView.java
  target/classes/Application/MarketService.class
  target/classes/Application/StoreService.class
  target/classes/Domain/Pair.class
  target/classes/Domain/Shopping/ShoppingBasket.class
  target/classes/Domain/Store/Feedback.class
  target/classes/Domain/Store/Store.class
  target/classes/Domain/Store/StoreFacade.class
  target/classes/Domain/User/Guest.class
  target/classes/Domain/User/IUserRepository.class
  target/classes/Domain/User/LoginManager.class
Labels: enhancement, server side

#163 HomePage, Login, Store Search screens
  src/main/java/UI/presenters/LoginPresenterMock.java
  src/main/java/UI/presenters/ProductPresenterMock.java
  src/main/java/UI/presenters/StorePresenterMock.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/LoginView.java
  src/main/java/UI/views/MainView.java
  src/main/java/UI/views/StoreSearchView.java
  target/classes/Application/MarketService.class
  target/classes/Application/StoreService.class
  target/classes/Domain/Pair.class
  target/classes/Domain/Shopping/ShoppingBasket.class
  target/classes/Domain/Store/Feedback.class
  target/classes/Domain/Store/Store.class
  target/classes/Domain/Store/StoreFacade.class
  target/classes/Domain/User/Guest.class
  target/classes/Domain/User/IUserRepository.class
  target/classes/Domain/User/LoginManager.class
Labels: enhancement, GUI

#172 implemented CartView completely
  src/main/java/UI/presenters/ProductPresenterMock.java
  src/main/java/UI/presenters/PurchasePresenterMock.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/CheckoutView.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/StoreSearchView.java
Labels: enhancement, GUI

#176 174 adding token usage to itemservice
  src/main/java/Application/ItemService.java
  src/test/java/MarketServiceTest.java
  src/test/java/StoreTests/ItemServiceTests.java
Labels: store, refactoring

#184 179 add product service
  src/main/java/Application/DTOs/CategoryDTO.java
  src/main/java/Application/DTOs/ProductDTO.java
  src/main/java/Application/ItemService.java
  src/main/java/Application/ProductService.java
  src/main/java/Domain/Store/IProductRepository.java
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Infrastructure/Repositories/MemoryProductRepository.java
  src/test/java/Domain/Store/ItemFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/ItemServiceTests.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: store, refactoring

#182 added LoginPresenter
  src/main/java/UI/presenters/LoginPresenter.java
Labels: enhancement, server side

#185 finished market presenter
  src/main/java/UI/presenters/IMarketPresenter.java
  src/main/java/UI/presenters/MarketPresenter.java
  target/classes/Application/MarketService.class
  target/classes/Application/StoreService.class
  target/classes/Domain/Store/Store.class
Labels: enhancement, server side

#187 180 implement imanagementpresenter
  src/main/java/Application/DTOs/CategoryDTO.java
  src/main/java/Application/DTOs/ProductDTO.java
  src/main/java/Application/ItemService.java
  src/main/java/Application/ProductService.java
  src/main/java/Domain/Store/IProductRepository.java
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Infrastructure/Repositories/MemoryProductRepository.java
  src/main/java/UI/presenters/IManagementPresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/test/java/Domain/Store/ItemFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/ItemServiceTests.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: enhancement, server side

#193 159 add permissionmanager
  pom.xml
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionManager.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: refactoring

#198 195 overhaul addproducttoinventory
  src/main/java/Application/ItemService.java
  src/main/java/Application/MarketService.java
  src/main/java/Domain/management/IMarketFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionManager.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/StoreTests/ItemServiceTests.java
Labels: refactoring

#192 191 implement `PurchasePresenter` and revamp `IPurchasePresenter` and fix `PurchasePresenterMock`
  src/main/java/Application/ShoppingService.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenterMock.java
Labels: enhancement, server side, refactoring

#203 Fixsing compilation issues and project structure issues
  .gitignore
  frontend/index.html
  src/main/frontend/index.html
  src/main/frontend/vite.confg.ts
  src/main/java/UI/MockAppConfig.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/MarketPresenterMock.java
  src/main/java/UI/presenters/PurchasePresenterMock.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/CheckoutView.java
  src/main/java/UI/views/HomePageView.java
  src/main/resources/META-INF/resources/config/flow-build-info.json
  src/test/java/StoreTests/StoreServiceTests.java
Labels: bug, common, server side, GUI

#205 Added a review view for feedback and rating
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/ProductReviewView.java
Labels: GUI

#218 217 add initialization managers
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/IRepoManager.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Infrastructure/MemoryRepoManager.java
Labels: refactoring

#219 199 overhaul itemservice to use permission manager
  src/main/java/Application/ItemService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/IRepoManager.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Domain/management/IPermissionRepository.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionFactory.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/Domain/management/PermissionType.java
  src/main/java/Infrastructure/MemoryRepoManager.java
  src/main/java/Infrastructure/Repositories/MemoryPermissionRepository.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/PermissionTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
  src/test/java/StoreTests/ItemServiceTests.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: refactoring

#220 213 add cartdto for cartview
  src/main/java/Application/DTOs/CartDTO.java
  src/main/java/Application/DTOs/ItemDTO.java
  src/main/java/Application/DTOs/ShoppingBasketDTO.java
  src/main/java/Application/ShoppingService.java
  src/test/java/ShoppingServiceTest.java
Labels: shopping, refactoring

#222 158 deconstruction of marketservice and marketfacade and permission system usage refactoring
  src/main/java/Application/CustomerServiceService.java
  src/main/java/Application/ItemService.java
  src/main/java/Application/MarketService.java
  src/main/java/Application/ProductService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/Store/Feedback.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/management/IMarketFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/Infrastructure/Repositories/MemoryFeedbackRepository.java
  src/main/java/UI/presenters/ProductPresenterMock.java
  src/main/java/UI/views/HomePageView.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
  src/test/java/Domain/Store/ItemFacadeTest.java
  src/test/java/Infrastructure/Repositories/MemoryShoppingBasketRepositoryTest.java
  src/test/java/Infrastructure/Repositories/MemoryShoppingCartRepositoryTest.java
  src/test/java/Infrastructure/Repositories/MemoryUserRepositoryTest.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
  src/test/java/StoreTests/ItemServiceTests.java
  src/test/java/StoreTests/StoreFacadeTests.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: users, store, shopping, refactoring, tests

#225 Refactor Auction Bidding Flow and Add Bid Acceptance Logic
  frontend/index.html
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/Shopping/IShoppingCartFacade.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/Auction.java
  src/main/java/Domain/Store/StoreFacade.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/StoreFacadeTests.java
Labels: store, shopping

#223 158 deconstruction of marketservice and marketfacade and permission system usage refactoring
  .gitignore
  src/main/frontend/index.html
  src/main/frontend/vite.confg.ts
  src/main/java/Application/CustomerServiceService.java
  src/main/java/Application/ItemService.java
  src/main/java/Application/MarketService.java
  src/main/java/Application/ProductService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Application/TokenService.java
  src/main/java/Application/UserService.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/Feedback.java
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/Domain/Store/ItemFilter.java
  src/main/java/Domain/Store/Product.java
  src/main/java/Domain/Store/Store.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/User/User.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Infrastructure/Repositories/MemoryAuctionRepository.java
  src/main/java/Infrastructure/Repositories/MemoryFeedbackRepository.java
  src/main/java/Infrastructure/Repositories/MemoryItemRepository.java
  src/main/java/Infrastructure/Repositories/MemoryPermissionRepository.java
  src/main/java/Infrastructure/Repositories/MemoryProductRepository.java
  src/main/java/Infrastructure/Repositories/MemoryReceiptRepository.java
  src/main/java/Infrastructure/Repositories/MemoryShoppingBasketRepository.java
  src/main/java/Infrastructure/Repositories/MemoryShoppingCartRepository.java
  src/main/java/Infrastructure/Repositories/MemoryStoreRepository.java
  src/main/java/Infrastructure/Repositories/MemoryUserRepository.java
  src/main/java/UI/GamazonApplication.java
  src/main/java/UI/MockAppConfig.java
  src/main/java/UI/presenters/IManagementPresenter.java
  src/main/java/UI/presenters/IMarketPresenter.java
  src/main/java/UI/presenters/IProductPresenter.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/LoginPresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/main/java/UI/presenters/MarketPresenter.java
  src/main/java/UI/presenters/MarketPresenterMock.java
  src/main/java/UI/presenters/ProductPresenter.java
  src/main/java/UI/presenters/ProductPresenterMock.java
  src/main/java/UI/presenters/PurchasePresenterMock.java
  src/main/java/UI/presenters/StorePresenter.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/CheckoutView.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/StoreSearchView.java
  src/main/resources/META-INF/resources/config/flow-build-info.json
  src/main/resources/application.properties
  src/test/java/MarketServiceTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
  src/test/java/StoreTests/StoreServiceTests.java
  src/test/java/UserServiceTests.java
Labels: refactoring

#228 V1 fixes
  .gitignore
  pom.xml
  src/main/java/Application/CustomerServiceService.java
  src/main/java/Application/DTOs/CartDTO.java
  src/main/java/Application/DTOs/ItemDTO.java
  src/main/java/Application/DTOs/ShoppingBasketDTO.java
  src/main/java/Application/ItemService.java
  src/main/java/Application/MarketService.java
  src/main/java/Application/ProductService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Application/TokenService.java
  src/main/java/Application/UserService.java
  src/main/java/Domain/ExternalServices/INotificationService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/IRepoManager.java
  src/main/java/Domain/Shopping/IShoppingCartFacade.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/Auction.java
  src/main/java/Domain/Store/Feedback.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/management/IMarketFacade.java
  src/main/java/Domain/management/IPermissionRepository.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionFactory.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/Domain/management/PermissionType.java
  src/main/java/Infrastructure/MemoryRepoManager.java
  src/main/java/Infrastructure/NotificationService.java
  src/main/java/Infrastructure/Repositories/MemoryPermissionRepository.java
  src/main/java/UI/presenters/LoginPresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/main/java/UI/presenters/MarketPresenter.java
  src/main/java/UI/presenters/ProductPresenterMock.java
  src/main/java/UI/presenters/PurchasePresenterMock.java
  src/main/java/UI/views/HomePageView.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
  src/test/java/Domain/Store/ItemFacadeTest.java
  src/test/java/Infrastructure/Repositories/MemoryShoppingBasketRepositoryTest.java
  src/test/java/Infrastructure/Repositories/MemoryShoppingCartRepositoryTest.java
  src/test/java/Infrastructure/Repositories/MemoryUserRepositoryTest.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/PermissionTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
  src/test/java/StoreTests/ItemServiceTests.java
  src/test/java/StoreTests/StoreFacadeTests.java
  src/test/java/StoreTests/StoreServiceTests.java
  src/test/java/UserServiceTests.java
Labels: refactoring

#231 Added AppInitializer which initialize the program with enteties
  src/main/frontend/index.html
  src/main/java/Application/MarketService.java
  src/main/java/Application/ProductService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/UI/AppInitializer.java
Labels: enhancement, server side

#236 changed product presenter and its interface
  pom.xml
  src/main/java/Application/utils/Notifier.java
  src/main/java/Infrastructure/WebSocketConfig.java
  src/main/java/Infrastructure/WebSocketNotifier.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenter.java
Labels: refactoring

#243 completed transition
  src/main/java/Application/DTOs/CartDTO.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenterMock.java
  src/main/java/UI/views/CartView.java
Labels: bug, GUI

#246 added item rating
  src/main/java/Application/ItemService.java
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/UI/presenters/ProductPresenter.java
Labels: bug, store, refactoring

#253 212 fix cart and checkout view
  log.txt.lck
  src/main/java/Domain/Store/ItemFacade.java
  src/main/java/Infrastructure/Repositories/MemoryProductRepository.java
  src/main/java/UI/presenters/IPurchasePresenter.java
  src/main/java/UI/presenters/PurchasePresenter.java
  src/main/java/UI/views/BasketLayout.java
  src/main/java/UI/views/CartView.java
Labels: bug, GUI

#258 241 implement real time per user websocket notifications without spring security
  log.txt.lck
  src/main/bundles/README.md
  src/main/bundles/dev.bundle
  src/main/frontend/ws-client.js
  src/main/java/Domain/ExternalServices/INotificationService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Infrastructure/NotificationService.java
  src/main/java/Infrastructure/WebSocketConfig.java
  src/main/java/Infrastructure/WebSocketNotifier.java
  src/main/java/UI/presenters/IUserSessionPresenter.java
  src/main/java/UI/presenters/UserSessionPresenter.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/webSocketConfigurations/StompPrincipal.java
  src/main/java/UI/webSocketConfigurations/UserIdChannelInterceptor.java
  src/main/java/UI/webSocketConfigurations/WebSocketConfig.java
  src/main/java/UI/webSocketConfigurations/WebSocketNotificationService.java
  src/main/java/UI/webSocketConfigurations/WebSocketNotifier.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
  src/test/java/StoreTests/StoreFacadeTests.java
  src/test/java/StoreTests/StoreServiceTests.java
  vite.config.ts
Labels: enhancement, store, server side

#261 done
  src/main/java/UI/webSocketConfigurations/ConnectedUserRegistry.java
  src/main/java/UI/webSocketConfigurations/UserIdChannelInterceptor.java
  src/main/java/UI/webSocketConfigurations/WebSocketNotificationService.java
Labels: server side

#265 255 add item to store functionality
  frontend/vite.confg.ts
  frontend/ws-client.js
  log.txt.lck
  src/main/java/Application/ItemService.java
  src/main/java/Application/ProductService.java
  src/main/java/Domain/Store/IProductRepository.java
  src/main/java/Domain/Store/ProductFacade.java
  src/main/java/Infrastructure/Repositories/MemoryProductRepository.java
  src/main/java/UI/presenters/IProductPresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/main/java/UI/presenters/ManagementPresenterMock.java
  src/main/java/UI/presenters/ProductPresenter.java
  src/main/java/UI/presenters/ProductPresenterMock.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/ManagerView.java
  src/main/java/UI/views/ProductReviewView.java
  src/main/java/UI/views/StoreSearchView.java
  src/main/java/UI/views/components/AddItemForm.java
  src/main/java/UI/views/components/BasketLayout.java
Labels: enhancement, GUI

#268 Added JaCoCo code coverage plugin configuration to pom.xml
  pom.xml
Labels: enhancement

#270 added name rto basketdto
  src/main/java/Application/DTOs/ShoppingBasketDTO.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Domain/Shopping/IShoppingCartFacade.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Domain/Store/StoreFacade.java
Labels: bug, enhancement, refactoring

#276 259 add user ban
  src/main/java/Application/CustomerServiceService.java
  src/main/java/Application/ItemService.java
  src/main/java/Application/MarketService.java
  src/main/java/Application/ProductService.java
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/management/IMarketFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionFactory.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/Domain/management/PermissionType.java
  src/main/java/Domain/management/RoleType.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
Labels: enhancement

#302 added banUser to service
  log.txt.lck
  src/main/java/Application/MarketService.java
Labels: market management, domain

#304 282 add date to permissions for ban user
  src/main/java/Domain/management/Permission.java
  src/main/java/Domain/management/PermissionManager.java
Labels: market management, domain

#307 305 close store in trading view
  src/main/frontend/ws-client.js
  src/main/java/Application/ServiceManager.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/Shopping/IShoppingCartFacade.java
  src/main/java/Domain/Shopping/IShoppingCartRepository.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Infrastructure/Repositories/MemoryShoppingCartRepository.java
  src/main/java/UI/presenters/ITradingPresenter.java
  src/main/java/UI/presenters/IUserSessionPresenter.java
  src/main/java/UI/presenters/TradingPresenter.java
  src/main/java/UI/presenters/UserSessionPresenter.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/LoginView.java
  src/main/java/UI/views/StoreSearchView.java
  src/main/java/UI/views/TradingView.java
  src/main/java/UI/views/components/StoreLayout.java
Labels: GUI

#309 Add temporary store closure functionality
  src/main/java/Application/DTOs/StoreDTO.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/Store/Store.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/UI/presenters/IManagementPresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/main/java/UI/views/CartView.java
  src/main/java/UI/views/ManagerView.java
Labels: enhancement, GUI

#315 311 ban unban watch banned users
  frontend/theme.ts
  frontend/vite.config.ts
  src/main/bundles/dev.bundle
  src/main/frontend/theme.ts
  src/main/frontend/vite.config.ts
  src/main/java/Application/MarketService.java
  src/main/java/Application/UserService.java
  src/main/java/Domain/User/LoginManager.java
  src/main/java/Domain/management/IMarketFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionFactory.java
  src/main/java/Domain/management/PermissionManager.java
  src/main/java/UI/presenters/ITradingPresenter.java
  src/main/java/UI/presenters/TradingPresenter.java
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/TradingView.java
Labels: enhancement, GUI

#326 Update HomePageView and ManagerView to use white text for improved vi…
  log.txt.lck
  src/main/java/UI/views/HomePageView.java
  src/main/java/UI/views/ManagerView.java
Labels: enhancement, GUI

#329 done
  src/main/bundles/dev.bundle
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Infrastructure/ExternalPaymentService.java
  src/main/java/UI/AppShellConfig.java
  src/test/java/Domain/Shopping/ShoppingCartFacadeTest.java
Labels: server side, refactoring

#333 added policies
  src/main/java/Application/DTOs/PoliciesDTOs/AndPolicyDTO.java
  src/main/java/Application/DTOs/PoliciesDTOs/CategoryAgePolicyDTO.java
  src/main/java/Application/DTOs/PoliciesDTOs/CategoryPolicyDTO.java
  src/main/java/Application/DTOs/PoliciesDTOs/IPolicyDTO.java
  src/main/java/Application/DTOs/PoliciesDTOs/MaxQuantityPolicyDTO.java
  src/main/java/Application/DTOs/PoliciesDTOs/MinQuantityPolicyDTO.java
  src/main/java/Application/PolicyService.java
  src/main/java/Domain/Store/IPolicyRepository.java
  src/main/java/Domain/Store/Policies/AndPolicy.java
  src/main/java/Domain/Store/Policies/CategoryAgePolicy.java
  src/main/java/Domain/Store/Policies/CategoryPolicy.java
  src/main/java/Domain/Store/Policies/IPolicy.java
  src/main/java/Domain/Store/Policies/MaxQuantityPolicy.java
  src/main/java/Domain/Store/Policies/MinQuantityPolicy.java
  src/main/java/Domain/User/Member.java
  src/main/java/Domain/management/PolicyFacade.java
  src/main/java/Infrastructure/Repositories/MemoryPolicyRepository.java
Labels: enhancement, server side

#336 316 real time notifications integration with gui
  src/main/bundles/dev.bundle
  src/main/bundles/prod.bundle
  src/main/java/Application/PolicyService.java
  src/main/java/Application/StoreService.java
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/UI/presenters/TradingPresenter.java
  src/main/java/UI/views/TradingView.java
  src/main/resources/application.properties
  src/test/java/StoreTests/StoreFacadeTests.java
Labels: enhancement, GUI

#342 330 bid fixes
  log.txt.lck
  src/main/bundles/dev.bundle
  src/main/java/Domain/Store/StoreFacade.java
  src/main/java/UI/views/HomePageView.java
  src/test/java/StoreTests/StoreFacadeTests.java
Labels: bug, domain

#346 324 fix management premissions
  src/main/bundles/dev.bundle
  src/main/java/Application/DTOs/UserDTO.java
  src/main/java/Application/MarketService.java
  src/main/java/Application/StoreService.java
  src/main/java/Application/UserService.java
  src/main/java/Domain/FacadeManager.java
  src/main/java/Domain/User/IUserRepository.java
  src/main/java/Domain/User/LoginManager.java
  src/main/java/Domain/management/IMarketFacade.java
  src/main/java/Domain/management/MarketFacade.java
  src/main/java/Domain/management/PermissionFactory.java
  src/main/java/Domain/management/PermissionType.java
  src/main/java/Infrastructure/Repositories/MemoryUserRepository.java
  src/main/java/UI/AppInitializer.java
  src/main/java/UI/presenters/ILoginPresenter.java
  src/main/java/UI/presenters/IManagementPresenter.java
  src/main/java/UI/presenters/IStorePresenter.java
  src/main/java/UI/presenters/LoginPresenter.java
  src/main/java/UI/presenters/ManagementPresenter.java
  src/main/java/UI/presenters/StorePresenter.java
  src/main/java/UI/views/ManagerView.java
  src/main/java/UI/views/UserProfileView.java
  src/main/java/UI/views/components/AddUserRoleDialog.java
  src/main/java/UI/views/components/ChangeUserRoleDialog.java
  src/main/java/UI/views/components/StoreLayout.java
  src/main/java/UI/views/components/StorePreviewDialog.java
  src/main/java/UI/views/components/UserPermissionsLayout.java
  src/main/java/UI/views/dataobjects/UserPermission.java
  src/test/java/Domain/User/LoginManagerTest.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
Labels: bug, refactoring, GUI, domain

#349 348 refactor tests
  src/main/java/Application/ServiceManager.java
  src/test/java/MarketFacadeTest.java
  src/test/java/MarketServiceTest.java
  src/test/java/ShoppingServiceTest.java
  src/test/java/StoreTests/CustomerServiceServiceTests.java
  src/test/java/StoreTests/StoreServiceTests.java
Labels: refactoring, tests, domain

#360 Added User to the DB.
  src/main/bundles/dev.bundle
  src/main/java/Domain/User/Guest.java
  src/main/java/Domain/User/Member.java
  src/main/java/Domain/User/User.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaUserSpringRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaProdConfig.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaUserSpringRepository.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryUserRepository.java
  src/main/java/UI/AppShellConfig.java
  src/main/java/UI/DatabaseCleaner.java
Labels: enhancement, DBs

#365 Refactor Receipt class for JPA persistence and update product handlin…
  src/main/bundles/dev.bundle
  src/main/java/Domain/Shopping/Receipt.java
  src/main/java/Domain/Shopping/ReceiptProduct.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaReceiptRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaItemRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaReceiptRepository.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryReceiptRepository.java
  src/main/java/UI/DatabaseCleaner.java
Labels: enhancement, DBs

#367 Refactor ShoppingService to improve cart and basket handling; ensure …
  src/main/java/Application/DTOs/CartDTO.java
  src/main/java/Application/DTOs/ShoppingBasketDTO.java
  src/main/java/Application/ShoppingService.java
  src/main/java/Domain/Shopping/ShoppingBasket.java
  src/main/java/Domain/Shopping/ShoppingBasketId.java
  src/main/java/Domain/Shopping/ShoppingCart.java
  src/main/java/Domain/Shopping/ShoppingCartFacade.java
  src/main/java/Infrastructure/JpaSpringRepositories/IJpaShoppingCartRepository.java
  src/main/java/Infrastructure/JpaSpringRepositories/JpaShoppingCartRepository.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryShoppingCartRepository.java
  src/main/java/UI/DatabaseCleaner.java
Labels: enhancement, DBs

#369 I did it
  src/main/java/Application/PolicyService.java
  src/main/java/Domain/management/PolicyFacade.java
  src/main/java/Infrastructure/MemoryRepositories/MemoryPolicyRepository.java
Labels: enhancement, refactoring
